# Please insert new items alphabetically.
eng:
  members:

  channel: "#engineering"

  exclude_titles:
    - WIP

  use_labels: true

  exclude_labels:
    - WIP

  quotes:
    - ":eggplant:"
    - "indeed"
    - "naming is hard"
