#members is intentionally left empty since this means 'all members of the github organization'
eng:
  members: []

  channel: "#engineering"

  exclude_titles:
    - WIP

  use_labels: true

  exclude_labels:
    - WIP
    - "needs update"
    - "proposal"
    - "waiting on requirements"

  quotes:
    - ":eggplant:"
    - "indeed"
    - "naming is hard"
