# Please insert new items alphabetically.
eng:
  members:
    - lklots
    - matteobanerjee
    - matthewferry
    - noahsilas
    - rachelleluyanlee
    - TJTorola
    - TylerBrock
    - ariisrael
    - isisAnchalee
    - loganmhb
    - manuelsabu
    - esarachan
    - gellingson
    - higgins
    - Lizard381
    - matthewferry
    - MatrixFrog
    - ibash
    - ninachaubal
    - richardharrington
    - caplis
    - Filip-F
    - kingdavidmartins
    - robertbourbonnais

  channel: "#engineering"

  exclude_titles:
    - WIP

  use_labels: true

  exclude_labels:
    - WIP

  quotes:
    - ":eggplant:"
    - "indeed"
    - "naming is hard"
